[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0


[env:motor_test]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200

; Собираем ТОЛЬКО эти файлы:
build_src_filter =
    +<../test/motor_test/src/main.cpp>
    +<../test/motor_test/src/motor.cpp>
    -<*>

; Добавляем include-папку для заголовков
build_flags =
    -I test/motor_test/include

[env:I2C_scanner_test]
platform = espressif32                       
board = esp32dev                  
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200

; Собираем ТОЛЬКО эти файлы:
build_src_filter =
    +<../test/i2c_scanner/main.cpp>
    -<*>
